# Generated by Django 4.2.16 on 2024-10-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='Uma imagem', max_length=20)),
                ('file_field', models.FileField(upload_to='files')),
                ('image_field', models.ImageField(upload_to='images')),
            ],
        ),
    ]
