# Generated by Django 4.2.16 on 2024-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0002_cadastroanimal_delete_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroanimal',
            name='image_field',
        ),
        migrations.AddField(
            model_name='cadastroanimal',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='cadastroanimal',
            name='sexo',
            field=models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], max_length=1),
        ),
    ]
