# Generated by Django 4.2.16 on 2024-10-15 18:13

from django.db import migrations, models
import site_abrigo.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0003_remove_cadastroanimal_image_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroanimal',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to=site_abrigo.models.upload_to),
        ),
    ]
