# Generated by Django 4.2.16 on 2024-10-16 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0004_alter_cadastroanimal_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroanimal',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastroanimal',
            name='disponivel_para_adocao',
            field=models.BooleanField(default=True),
        ),
    ]
