# Generated by Django 4.2.16 on 2024-10-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0005_cadastroanimal_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroanimal',
            name='especie',
            field=models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato'), ('OUTROS', 'Outros')], max_length=8),
        ),
    ]
