# Generated by Django 4.2.16 on 2024-10-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0006_alter_cadastroanimal_especie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastroanimal',
            old_name='imagens',
            new_name='imagem',
        ),
    ]
