# Generated by Django 4.2.16 on 2024-10-17 12:30

from django.db import migrations, models
import site_abrigo.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0007_rename_imagens_cadastroanimal_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroanimal',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Outros', 'Outros')], max_length=8),
        ),
        migrations.AlterField(
            model_name='cadastroanimal',
            name='imagem',
            field=models.ImageField(upload_to=site_abrigo.models.upload_to),
        ),
    ]
