# Generated by Django 4.2.16 on 2024-10-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0009_alter_cadastroanimal_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroanimal',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outros', 'Outros')], max_length=8),
        ),
        migrations.AlterField(
            model_name='cadastroanimal',
            name='raca',
            field=models.CharField(blank=True, default='Viralata', max_length=80),
        ),
        migrations.AlterField(
            model_name='cadastroanimal',
            name='sexo',
            field=models.CharField(choices=[('femea', 'Femêa'), ('macho', 'Macho')], max_length=5),
        ),
    ]
