# Generated by Django 4.2.16 on 2024-10-17 23:20

from django.db import migrations, models
import django.db.models.deletion
import site_abrigo.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0011_alter_cadastroanimal_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('imagem', models.ImageField(upload_to=site_abrigo.models.upload_to)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_abrigo.cadastroanimal')),
            ],
        ),
    ]
