# Generated by Django 4.2.16 on 2024-10-18 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0015_alter_galeriaimagem_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriaimagem',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='galeriaimagem',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='site_abrigo.cadastroanimal'),
        ),
    ]
