# Generated by Django 4.2.16 on 2024-10-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0015_alter_galeriaimagem_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroanimal',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='galeriaimagem',
            name='titulo',
        ),
        migrations.AddField(
            model_name='cadastroanimal',
            name='filhote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cadastroanimal',
            name='raca',
            field=models.CharField(blank=True, default='Viralata', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='galeriaimagem',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='site_abrigo.cadastroanimal'),
        ),
    ]
