# Generated by Django 4.2.16 on 2024-10-18 22:13

from django.db import migrations, models
import site_abrigo.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0016_remove_galeriaimagem_titulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastroanimal',
            options={'ordering': ['nome'], 'verbose_name': 'Cadastro de Animal', 'verbose_name_plural': 'Cadastro de Animais'},
        ),
        migrations.AlterModelOptions(
            name='galeriaimagem',
            options={'verbose_name': 'Imagem da Galeria', 'verbose_name_plural': 'Imagens da Galeria'},
        ),
        migrations.AlterField(
            model_name='cadastroanimal',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=site_abrigo.models.upload_to),
        ),
    ]
