# Generated by Django 4.2.16 on 2024-10-18 22:32

from django.db import migrations, models
import site_abrigo.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_abrigo', '0017_alter_cadastroanimal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroanimal',
            name='imagem',
            field=models.ImageField(upload_to=site_abrigo.models.upload_to),
        ),
    ]
